name: flutter_blbl
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.0+1
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  data_plugin: ^0.0.16
  json_serializable: ^2.0.0
  fluttertoast: ^8.0.6
  permission_handler: ^5.0.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    #加载文件夹中所有图片
    - images/
